---

# Main tasks file for generic-application role

- name: 'INIT | Manage variables to use for our target'
  import_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::generic-application'
    - 'role::generic-application::init'
